/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SessionsIndexImport } from './routes/sessions/index'
import { Route as SessionsIdImport } from './routes/sessions/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SessionsIndexRoute = SessionsIndexImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRoute,
} as any)

const SessionsIdRoute = SessionsIdImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdImport
      parentRoute: typeof rootRoute
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions': typeof SessionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions': typeof SessionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/sessions/': typeof SessionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sessions/$id' | '/sessions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sessions/$id' | '/sessions'
  id: '__root__' | '/' | '/sessions/$id' | '/sessions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionsIdRoute: typeof SessionsIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsIdRoute: SessionsIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sessions/$id",
        "/sessions/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sessions/$id": {
      "filePath": "sessions/$id.tsx"
    },
    "/sessions/": {
      "filePath": "sessions/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
